= Cues
James Elliott <james@deepsymmetry.org>
:icons: font

// Set up support for relative links on GitHub; add more conditions
// if you need to support other environments and extensions.
ifdef::env-github[:outfilesuffix: .adoc]

Cues are a convenient way to organize, identify, trigger, adjust, and
monitor effects. Each show in Afterglow maintains a cue grid, which
can be viewed and interacted with through the
http://deepsymmetry.org/afterglow/doc/afterglow.core.html#var-start-web-server[embedded
web interface] and MIDI controller mapping implementations which
register themselves as grid controllers, as does the
http://deepsymmetry.org/afterglow/doc/afterglow.controllers.ableton-push.html[Ableton
Push].

You can also trigger cues from simpler MIDI controllers which don't
register as grid controllers by explicitly mapping notes or control
changes to cues using
http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-add-midi-control-to-cue-mapping[afterglow.show/add-midi-control-to-cue-mapping].
Regardless of the mechanism by which a cue is triggered, the web
interface, a registered grid controller, or an explicitly mapped MIDI
note or control change, feedback will be sent to all interfaces so the
status of the cue will be represented consistently on all of them.

[[creating-cues]]
Creating Cues
~~~~~~~~~~~~~

The
http://deepsymmetry.org/afterglow/doc/afterglow.effects.cues.html[afterglow.effects.cues]
namespace provides functions for creating cues.

TODO: Describe the functions and arguments, link to effect examples.

[[controlling-cues]]
Controlling Cues
~~~~~~~~~~~~~~~~

The
http://deepsymmetry.org/afterglow/doc/afterglow.controllers.html[afterglow.controllers]
namespace defines some helpful functions for working with cues, and
defines a
http://deepsymmetry.org/afterglow/doc/afterglow.controllers.html#var-IGridController[grid
controller protocol] which rich controller mappings like the one for
the Ableton Push can use to attach themselves to a running show, and
synchronize with the web interface.

TODO: Flesh out, discuss individual functions.
