Oscillators in Afterglow are a flexible way of turning the timing
information tracked by metronomes into waveforms that can be used to
make lights do interesting things. They can be related to the beats or
bars of the metronome, or multiples or fractions thereof, and can be
sawtooth, triangle, square, or sine waves.
http://en.wikipedia.org/wiki/Sawtooth_wave[Wikipedia] has a nice
introduction to these waveforms. The namespace
`afterglow.effects.oscillator` has [[functions|oscillators]] for
creating lots of variations of them.

_____________________________________________________________________________________________________________________________________________________________________________________________________
These examples assume you are in a Clojure REPL with Afterglow loaded,
in the namespace `afterglow.examples`. This is the default namespace you
get if you check out the project and run `lein repl`.
_____________________________________________________________________________________________________________________________________________________________________________________________________

[[oscillator-effects]]
Oscillator Effects
~~~~~~~~~~~~~~~~~~

Here is one way to create a basic oscillated hue effect which cycles
through all colors over one bar of the show metronome:

code,clojure---------------------------------------------------------
code,clojure
(def hue-param (params/build-oscillated-param
                 (oscillators/sawtooth-bar) :max 360))
(show/add-effect! :color (global-color-cue
   (params/build-color-param :s 100 :l 50 :h hue-param)))
---------------------------------------------------------

___________________________________________________________________________________________________________________________________________________________________________________________
Remember that if you aren’t seeing anything when after assigning color
effects to a fixture to make sure you also have a dimmer effect setting
that fixture’s dimmer to some visible level.
___________________________________________________________________________________________________________________________________________________________________________________________

You can set up separate metronomes as show variables, so that effect
timing can be separate from the main show, which is intended to track
the beat of the music. Here we will create a metronome running at 5
beats per minute in a show variable we will call `timer`.

code,clojure---------------------------------------------- code,clojure
    (show/set-variable! :timer (metronome 50))
----------------------------------------------

Then we can build an oscillated hue parameter based on that timer, for a
nice, gradual color fade. We will use a sawtooth wave since it smoothly
goes from its minimum to its maximum value. Zero is the default minimum,
which is perfect, since it is the lowest hue value. We will tell the
oscillated parameter to range from that to a maximum of 360, the largest
hue. Since hues form a circle, we will fade smoothly around the circle
for each oscillation, with no jarring transition from one bar to the
next:

code,clojure-----------------------------------------------------------
code,clojure
(show/set-variable! :hue-param
  (params/build-oscillated-param (oscillators/sawtooth-bar)
    :metronome :timer :max 360))
-----------------------------------------------------------

Notice the use of the keyword `:timer` to tell `build-oscillated-param`
to use the show variable with that name for its `:metronome` keyword
parameter. We can do the same thing when building our color effect to
use this oscillated hue parameter variable:

code,clojure---------------------------------------------------------
code,clojure
(show/add-effect! :color (global-color-cue
  (params/build-color-param :s 100 :l 50 :h :hue-param)))
---------------------------------------------------------

You can change the speed of the fade by changing the BPM of the
metronome stored in the show variable:

code,clojure------------------------------------------ code,clojure
(metro-bpm (show/get-variable :timer) 500)
------------------------------------------

Suddenly it is crazy fast!

code,clojure---------------------------------------- code,clojure
(metro-bpm (show/get-variable :timer) 5)
----------------------------------------

Back to a sedate fade.

[[spatial-effects]]
Spatial Effects
~~~~~~~~~~~~~~~

Rather than spreading the rainbow out in time, how about if we spread it
physically across the lights in the show, in the form of a rainbow
gradient along the X axis?

code,clojure---------------------------------------------------------------------
code,clojure
(def hue-gradient (params/build-spatial-param (show/all-fixtures)
  (fn [head] (- (:x head) (:min-x @(:dimensions *show*)))) :end 360))
(show/add-effect! :color (global-color-cue
  (params/build-color-param :s 100 :l 50 :h hue-gradient)
                            :include-color-wheels true))
---------------------------------------------------------------------

___________________________________________________________________________________________________________________________
Since this cue is not constantly changing over time, it makes sense to
allow fixtures that use color wheels to participate.
___________________________________________________________________________________________________________________________

That’s pretty! But now that we have both of these interesting concepts,
oscillators and spatial gradients, wouldn’t it be nice if we could
combine them? Oh, but we can!

code,clojure----------------------------------------------------------------------
code,clojure
(def adjust-param
  (params/build-oscillated-param (oscillators/sawtooth-bar) :max 360))
(show/add-effect! :color (global-color-cue
  (params/build-color-param :s 100 :l 50 :h hue-gradient
                            :adjust-hue adjust-param)))
----------------------------------------------------------------------

__________________________________________________________________________________________________________________________________
Now the rainbow drifts across the whole lighting rig. We left out color
wheels this time, since the color is continually shifting.
__________________________________________________________________________________________________________________________________

The [[Effect Functions|effect-functions]] section gives more details
about how these effects work.
