= Fixture Definitions
James Elliott <james@deepsymmetry.org>
:icons: font

// Set up support for relative links on GitHub; add more conditions
// if you need to support other environments and extensions.
ifdef::env-github[:outfilesuffix: .adoc]

Fixture definitions tell afterglow what capabilities a given piece of
lighting hardware has, and how to control it to get the effects that are
being requested.

There are a vast number of fixture types out there, and at this early
stage almost none of them are built in to Afterglow, so you will
probably need to create your own. You can study the existing fixture
definitions for examples of how it is done. You can also ask for help
on the https://github.com/brunchboy/afterglow/wiki/Questions[wiki].

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.html[afterglow.fixtures]
has definitions for very basic one-channel generic dimmers and
switches. Looking at the source for those can illustrate the most
basic structure of a fixture definition. It also contains some helper
functions Afterglow uses in processing fixture definitions.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.american-dj.html[afterglow.fixtures.american-dj]
contains definitions for fixtures made by American DJ. Currently, only
the Hypnotic RGB laser is present.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.blizzard.html[afterglow.fixtures.blizzard]
is the most complete so far, mostly because the author lives close to
Blizzard and mostly owns fixures made by them. It includes definitions
for a full-featured moving head spot (the Torrent F3), a moving head
color-mixing LED fixture (the Blade RGBW), an LED five-color Par (the
Puck Fab5), an eight-head RGB system (the Weather System), and an RGBW
moonflower effect (the Snowball). These might be useful examples for
fixtures you want to create.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.chauvet.html[afterglow.fixtures.chauvet]
is for fixtures made by Chauvet. The only one in there so far is for a
six-color (RGB, amber, white, and ultraviolet) LED Par.

== Structure of a Fixture Definition

Once created, a fixture definition is simply a Clojure map with keys
and values that tell Afterglow how to control it. The fixture
definition functions linked to above simply create and return these
maps.

Fixtures may have multiple _modes_ which change the number and meaning
of the control channels they use. For such fixtures, the mode is
generally given as an argument to the fixture definition function, and
tells it what version of the map to return. For convenience, the
function may let you call it with no argument, and assume a default
mode. Its documentation should reflect this, see for example the
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.blizzard.html#var-blade-rgbw[blade-rgbw]
documentation.

When you are learning how to write fixture definitions, it can be
helpful to compare the fixture definition functions, which call helper
functions described on this page, with the actual maps that they
return. This can be facilitated by using `clojure.pprint/pprint` to
pretty-print the map that you get when calling the function. For
example:

[source,clojure]
----
(clojure.pprint/pprint (afterglow.fixtures.blizzard/snowball))
; {:name "Blizzard Snowball",
;  :channels
;  [{:offset 1,
;    :type :dimmer,
;    :functions
;    [{:start 0,
;      :end 255,
;      :range :variable,
;      :type :dimmer,
;      :label "Dimmer"}]}
;   {:offset 2,
;    :type :color,
;    :functions
;    [{:start 0, :end 255, :range :variable, :type :red, :label "Red"}],
;    :color :red}
; [...many channels omitted for brevity...]
;   {:offset 9,
;    :type :control,
;    :functions
;    [{:start 0,
;      :range :fixed,
;      :type :no-function,
;      :label "No function",
;      :end 127}
;     {:range :variable,
;      :label "Sound-active",
;      :type :sound-active,
;      :var-label "Sensitivity",
;      :start 128,
;      :end 255}]}]}
; -> nil
----


TODO: Finish this page.

* Document how to write them, analyzing examples like the
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.blizzard.html[Blizzard]
definitions, with special attention on how to document default
orientations and head positions with respect to
<<show_space#show-space,show space>> so the geometry
works out.

* Explain how to create function specifications in all their variations,
with range helpers, etc., and list naming conventions established so
far, so that new fixtures can participate when they have similar
capabilities.
