= Fixture Definitions
James Elliott <james@deepsymmetry.org>
:icons: font

// Set up support for relative links on GitHub; add more conditions
// if you need to support other environments and extensions.
ifdef::env-github[:outfilesuffix: .adoc]

Fixture definitions tell afterglow what capabilities a given piece of
lighting hardware has, and how to control it to get the effects that are
being requested.

There are a vast number of fixture types out there, and at this early
stage almost none of them are built in to Afterglow, so you will
probably need to create your own. You can study the existing fixture
definitions for examples of how it is done. You can also ask for help
on the https://github.com/brunchboy/afterglow/wiki/Questions[wiki].

TIP: When you first embark on the project of creating a fixture
definition, it might seem overwhelming. This page is long, and
includes a great deal of complicated detail. But don't despair! First,
remember that most fixtures only do a subset of the kinds of things
that the fixture definition mechanism needs to handle, so you do not
need to learn and understand all of it at once. And even more helpful
to beginners, realize that you do not need to finish your fixture
definition before you can start using and testing it. Your fixture may
be capable of many things, but start out by defining just a couple of
channels that will make it at least light up, and see if you can get
those working in a show. Once they are, you can already use the
fixture at least at that level. And that success can be a foundation
for digging deeper into other types of channels, which you can add to
your definition one at a time, building on what you learn as you go
along.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.html[afterglow.fixtures]
has definitions for very basic one-channel generic dimmers and
switches. Looking at the source for those can illustrate the most
basic structure of a fixture definition. It also contains some helper
functions Afterglow uses in processing fixture definitions.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.american-dj.html[afterglow.fixtures.american-dj]
contains definitions for fixtures made by American DJ. Currently, only
the Hypnotic RGB laser is present.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.blizzard.html[afterglow.fixtures.blizzard]
is the most complete so far, mostly because the author lives close to
Blizzard and mostly owns fixures made by them. It includes definitions
for a full-featured moving head spot (the Torrent F3), a moving head
color-mixing LED fixture (the Blade RGBW), an LED five-color Par (the
Puck Fab5), an eight-head RGB system (the Weather System), and an RGBW
moonflower effect (the Snowball). These might be useful examples for
fixtures you want to create.

The namespace
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.chauvet.html[afterglow.fixtures.chauvet]
is for fixtures made by Chauvet. The only one in there so far is for a
six-color (RGB, amber, white, and ultraviolet) LED Par.

== Structure of a Fixture Definition

Once created, a fixture definition is simply a Clojure map with keys
and values that tell Afterglow how to control it. The fixture
definition functions linked to above simply create and return these
maps.

Fixtures may have multiple "personalities" or _modes_ which change the
number and meaning of the control channels they use, and the features
that are available. For such fixtures, the mode is generally given as
an argument to the fixture definition function, and tells it what
version of the map to return. For convenience, the function may let
you call it with no argument, and assume a default mode. Its
documentation should reflect this, see for example the
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.blizzard.html#var-blade-rgbw[blade-rgbw]
documentation.

When you are learning how to write fixture definitions, it can be
helpful to compare the fixture definition functions, which call helper
functions described on this page, with the actual maps that they
return. This can be facilitated by using `clojure.pprint/pprint` to
pretty-print the map that you get when calling the function. For
example:

[source,clojure]
----
(clojure.pprint/pprint (afterglow.fixtures.blizzard/snowball))
; {:name "Blizzard Snowball",
;  :channels
;  [{:offset 1,
;    :type :dimmer,
;    :functions
;    [{:start 0,
;      :end 255,
;      :range :variable,
;      :type :dimmer,
;      :label "Dimmer"}]}
;   {:offset 2,
;    :type :color,
;    :functions
;    [{:start 0, :end 255, :range :variable, :type :red, :label "Red"}],
;    :color :red}
; [...many channels omitted for brevity...]
;   {:offset 9,
;    :type :control,
;    :functions
;    [{:start 0,
;      :range :fixed,
;      :type :no-function,
;      :label "No function",
;      :end 127}
;     {:range :variable,
;      :label "Sound-active",
;      :type :sound-active,
;      :var-label "Sensitivity",
;      :start 128,
;      :end 255}]}]}
; -> nil
----

Even though most of the channels were cut out to shorten that example,
it is still pretty long. Still, it gives a sense of the shape of a
fixture definition. You may have noticed that there were only two
top-level keys in the returned map, `:name` and `:channels`. Those
are the only two that need to be there for a simple fixture. And
almost all of the information Afterglow needs is found in the
`:channels` list, so that is where you will spend most of your work in
creating the fixture definition.

If you had already looked at the source for
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.blizzard.html#var-snowball[snowball]
(which you can get to by clicking the `view source` button at the
bottom of all the API documentation entries), you might have noticed
that the source is a lot shorter than the resulting map. That's
because it can take advantage of a bunch of helper functions described
on this page to help with the tedious and repetetive parts of
constructing the map. And when you patch a fixture into a show using
http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-patch-fixture.21[afterglow.show/patch-fixture!]
the map gets much bigger again, as Afterglow annotates it with
information you provided during the patching process, assigning the
actual universes and DMX channels for each logical channel in the
fixture definition, and figuring out the location in space and aiming
direction, potentially of several heads of a multi-head fixture.

So, let's look at the fixture definition map contents in detail.

[cols="2l,5a", options="header"]
|===
|Key
|Purpose

|:name

|A string which identifies the manufacturer and model of fixture.

|:channels

| A list of channel specifications which tell Afterglow about the DMX
channels that the fixture responds to, and how to make it do different
things. This is the meat of the fixture definition, and is described
in detail <<channel-specifications,below>>.

|:mode

|If present, identifies the fixture mode in which this definition map
 was created. As desrcibed above, some fixtures can be configured to
 have different &ldquo;personalities&rdquo; which use a different
 number of DMX channels and provide a different set of features. Their
 fixture definition functions will use a `mode` argument to determine
 the mode in which the fixture is operating, and return an appropriate
 map. That map will include the chosen mode keyword as the value at
 this key.

|:heads

|If a fixture has multiple independent heads, which can be controlled
 individually, the channels which control the heads are grouped into a
 list under this key. Each entry in the list is a map which explains a
 single head. It will contain its own `:channels` key with the channel
 specifications controlling that specific head, and will also contain
 geometric information about the offset of that particular head from
 the geometric center of the fixture, so Afterglow can figure out
 where the head is in space when the fiture is patched into the show.
 This is described in more detail <<head-specifications,below>>.

|:pan-center

|If this fixture is a moving head capable of pan movements, this entry
 tells afterglow the DMX value to send the fixture to pan it directly
 at the audience when the fixture is hung at its standard orientation.
 (The documentation you create for your fixture definition needs to
 explain what this default orientation is, so that people patching
 your fixture can figure out the proper angle information to tell
 Afterglow if they hung it in a different orientation, as explained in
 <<show_space#show-space,Show Space>>.) The `:pan-center` value should
 pan the light so it is aimed exactly along the show Z axis when also
 tilted to `:tilt-center`.

Many fixtures can pan more than once around a full circle, so you may
have a choice of values to supply here, all of which pan the fixture
directly towards the audience in your default hanging orientation. If
so, pick one towards the middle of the DMX range, giving Afterglow
room to maneuver without having to flip to the opposite end of the pan
range regardless of how the fixture has been hung.

If the fixture cannot pan far enough to aim directly at the audience
when it is hung in its default orientation, you may be better off
choosing a different default hanging orientation. But if you do not
want to do that, you can set this to the closest value outside the
legal DMX range which would cause the fixture to pan that far if it
were legal and possible, and Afterglow will still be able to figure
out and use the legal movements that the fixture is capable of.

|:pan-half-circle

|If this fixture is a moving head capable of pan movements, this entry
 tells Afterglow the amount it needs to add to the DMX value sent on
 the fixture's Pan channel to pan it halfway around a circle in a
 counterclockwise direction. Afterglow uses this to figure out how to
 aim the head exactly where you want it. If your fixture is not
 capable of panning that far, this value may be larger than a legal
 DMX value. That is fine, Afterglow will figure that out. Simply
 always give it the value which, when added to some legal Pan channel
 value, would cause the fixture to rotate counterclockwise halfway
 around a circle if it could rotate that far. (This number could be
 negative if the fixture turns clockwise when the pan value is
 increased in its default hanging orientation.)

The <<show_space#show-space,Show Space>> page explains how to figure
out which rotations are clockwise or counterclockwise with respect to
different axes. Pan motions are rotations around the fixture Y axis.

|:tilt-center

|If this fixture is a moving head capable of tilt movements, this
 entry tells afterglow the DMX value to send the fixture to tilt it
 directly at the audience when the fixture is hung at its standard
 orientation. (The documentation you create for your fixture
 definition needs to explain what this default orientation is, so that
 people patching your fixture can figure out the proper angle
 information to tell Afterglow if they hung it in a different
 orientation, as explained in <<show_space#show-space,Show Space>>.)
 The `:tilt-center` value should tilt the light so it is aimed exactly
 along the show Z axis when also panned to `:pan-center`.

Some fixtures can tilt more than once around a full circle, so you may
have a choice of values to supply here, all of which tilt the fixture
directly towards the audience in your default hanging orientation. If
so, pick one towards the middle of the DMX range, giving Afterglow
room to maneuver without having to flip to the opposite end of the tilt
range regardless of how the fixture has been hung.

If the fixture cannot tilt far enough to aim directly at the audience
when it is hung in its default orientation, you may be better off
choosing a different default hanging orientation. But if you do not
want to do that, you can set this to the closest value outside the
legal DMX range which would cause the fixture to tilt that far if it
were legal and possible, and Afterglow will still be able to figure
out and use the legal movements that the fixture is capable of.

|:tilt-half-circle

|If this fixture is a moving head capable of tilt movements, this entry
 tells Afterglow the amount it needs to add to the DMX value sent on
 the fixture's Tilt channel to tilt it halfway around a circle in a
 counterclockwise direction. Afterglow uses this to figure out how to
 aim the head exactly where you want it. If your fixture is not
 capable of tilting that far, this value may be larger than a legal
 DMX value. That is fine, Afterglow will figure that out. Simply
 always give it the value which, when added to some legal Tilt channel
 value, would cause the fixture to rotate counterclockwise halfway
 around a circle if it could rotate that far. (This number could be
 negative if the fixture turns clockwise when the tilt value is
 increased in its default hanging orientation.)

The <<show_space#show-space,Show Space>> page explains how to figure
out which rotations are clockwise or counterclockwise with respect to
different axes. Tilt motions are rotations around the fixture X axis.

|===

=== Channel Specifications

The `:channels` entry for a fixture or head definition map tells
Afterglow the control channels that can be used to make that fixture
or head do things. It is a list of maps, each of which describes the
nature and capabilities of a single channel that the fixture or head
responds to.

TIP: Although there is a lot of detail in this table, you don't
necessarily need to understand it all to create fixture definitions,
because Afterglow provides <<channel-creation-functions,channel
creation functions>> to create these maps for you.

Each channel specification map has the following content:

[cols="2l,5a", options="header"]
|===
|Key
|Purpose

|:offset

|The number that identifies the channel. Each fixture listens to one
 or more channels, and is itself configured to a partcular DMX channel
 number (DMX channels range from 1 to 512). That configuration defines
 the _first_ channel the fixture listens to. The `:offset` value tells
 Afterglow how the current channel specification relates to the
 fixture's configured (starting) channel number. An offset of `1`
 corresponds to the first channel the fixture is listening to, which
 would be the channel number configured on the fixture's front panel
 (or via its DIP switches or jumpers if it is really old-school). The
 second channel would have offset `2`, and would correspond to the
 channel one greater than the fixture is configured to listen to.

Although it might seem more natural (at least to a programmer) to
start the offset with `0`, because then you could calculate the actual
channel number by simply adding the offset to the address at which the
fixture is configured to listen, most lighting manuals describe their
fixture channels with numbers that start with `1`, so Afterglow
follows that convention.

The offsets for all the channel specifications in a fixture definition
should form a continuous series of integers starting from 1 and going
up to the number of channels the fixture supports. It is an error if
more than one channel specification in the fixture definition uses the
same offset value, and if there are any gaps it probably means that
you have missed a channel specification (except for multi-byte
channels, as described in the next row). You don't need to define the
channels in the same order as their offsets in your fixture
definition, although that is a reasonable practice, making it easier
to match them up with the manual.

|:fine-offset

|There is one circumstance in which there _will_ be gaps in the
`:offset` values for your channel definitions. Sometimes a pair of
channels are used to express a single value, such as pan, tilt, or a
dimmer level, because the normal DMX value range, from 0 to 255, does
not give enough precision to allow smooth movements or fades. In those
cases, you specify the channel number containing the
most-significant-byte (MSB) of the value as the `:offset`, and the
channel containing the least-significant-byte (LSB) is specified in
the same channel specification using the key `:fine-offset`. The
function
http://deepsymmetry.org/afterglow/doc/afterglow.channels.html#var-fine-channel[afterglow.channels/fine-channel]
helps create such a channel specification map. (In fact, it has other
handy features which make it useful even when you are creating a
channel specification that does not need a `:fine-offset` value).

|:type

|Tells afterglow the kind of channel this is. Special values include
 `:color` for a channel that contains a color intensity, `:dimmer` for
 controlling brightness independent of color, and `:pan` and `:tilt`
 for controlling moving heads. Other channels may use keywords that
 Afterglow does not recognize. A common keyword used for a grab-bag
 channel which may do many things depending on the exact DMX value
 sent is `:control`.

|:color

|When the channel `:type` is `:color`, this key is also present to
 tell Afterglow what color the channel controls the intensity of.
 Afterglow uses this information to enable color mixing using multiple
 color channels. The value of this key will be a keyword. The values
 `:red`, `:green`, `:blue`, and `:white` are understood and supported
 for color mixing automatically. If your fixture has LEDs of other
 colors and you would like Afterglow to include them in its color
 mixing calculations, in addition to supplying a `:color` value for
 their channel, you will need to specify a `:hue` value (below), so
 Afterglow knows how to mix them in.

|:hue

[[hue-mixing]]
|When the channel `:type` is `:color`, this key is optionally present
 to tell Afterglow the hue value of the LEDs controlled by the
 channel. This allows Afterglow to perform color mixing with
 non-standard LED colors. Its value is the numeric hue (expressed in
 terms of degrees around the color circle) of the LEDs. The best way
 to find that is with a colorimeter, but since most of us can't afford
 them, you can approximate it by working with graphic design software,
 or even entering the color name on
 https://www.wolframalpha.com[Wolfram Alpha].

If you don't want Afterglow to mix colors using this channel, leave
out the `:hue` entry. The fixture definition function for the Chauvet
http://deepsymmetry.org/afterglow/doc/afterglow.fixtures.chauvet.html#var-slimpar-hex3-irc[SlimPar
Hex3 IRC] uses optional keyword arguments to let the show creator
decide whether or not to include them for its amber and ultraviolet
channels.

|:functions

|A list of <<function-specifications,Function Specifications>> which
 identify ranges of DMX values that can be sent to the channel, and
 which perform particular functions. Fixture manufacturers often use a
 single DMX channel to achieve many different kinds of effects, in
 order to not use up the DMX address space, especially when it would
 not make sense to try to activate two or more of the functions at the
 same time. Afterglow effects and cues can work in terms of these
 function definitions, and it often makes sense to do so even for
 channels which implement only a single function, so you don't need to
 worry about how a function is implemented when designing your effect
 or cue. Because of that, the channel creation functions add a
 function map even when you are creating a single-function channel.

|===

=== Head Specifications

As described above, the `:heads` entry in a fixture definition map is
a list that describes each individually controllable head within that
fixture. It may be a separate moving head, or it may just be an
individually-addressable pixel. Each element of the list is a map with
the following content:

[cols="2l,5a", options="header"]
|===
|Key
|Purpose

|:channels

| A list of channel specifications which tell Afterglow about the DMX
channels that this individual head responds to. These have exactly the
same structure as the channel specifications for the main fixture, as
described <<channel-specifications,above>>. A channel can only be
listed in one place or the other. If it affects the entire fixture, it
should be in the main list; if it affects only a single head, it
should be in that head's list.

|:x

|The offset along the fixture X axis, in meters, from the geometric
 center of the fixture (the point at which Afterglow is told the
 fixture is located when patching the fixture) and the geometric
 center of this head. If this head is centered along the fixture X
 axis, you can omit this value or you can supply it with a value of
 0.0. The <<show_space#show-space,Show Space>> page illustrates the
 axes and links to a function you can use for converting inches to
 meters.

|:y

|The offset along the fixture Y axis, in meters, from the geometric
 center of the fixture (the point at which Afterglow is told the
 fixture is located when patching the fixture) and the geometric
 center of this head. If this head is centered along the fixture Y
 axis, you can omit this value or you can supply it with a value of
 0.0. The <<show_space#show-space,Show Space>> page illustrates the
 axes and links to a function you can use for converting inches to
 meters.

|:z

|The offset along the fixture Z axis, in meters, from the geometric
 center of the fixture (the point at which Afterglow is told the
 fixture is located when patching the fixture) and the geometric
 center of this head. If this head is centered along the fixture X
 axis, you can omit this value or you can supply it with a value of
 0.0. The <<show_space#show-space,Show Space>> page illustrates the
 axes and links to a function you can use for converting inches to
 meters.

|:x-rotation

|If this head aims in a different direction than the fixture as a
 whole, this value tells afterglow the angle in radians it is rotated
 around the X axis. The <<show_space#show-space,Show Space>> page
 illustrates the axes, explains how to calculate the sign of a
 rotation, and links to a function you can use for converting degrees
 to radians.

|:y-rotation

|If this head aims in a different direction than the fixture as a
 whole, this value tells afterglow the angle in radians it is rotated
 around the Y axis. The <<show_space#show-space,Show Space>> page
 illustrates the axes, explains how to calculate the sign of a
 rotation, and links to a function you can use for converting degrees
 to radians.

|:z-rotation

|If this head aims in a different direction than the fixture as a
 whole, this value tells afterglow the angle in radians it is rotated
 around the Z axis. The <<show_space#show-space,Show Space>> page
 illustrates the axes, explains how to calculate the sign of a
 rotation, and links to a function you can use for converting degrees
 to radians.

|===

=== Function Specifications

Function specifications allow a single channel to be broken up into a
series of value ranges which accomplish different purposes. As noted
above, fixture manufacturers often do this so that they can provide a
lot of functionality without taking up too much of the DMX address
space. And since fixtures often have functions which cannot be
activated at the same time, such as selecting a particular gobo on a
gobo wheel, it makes great sense.

The `:functions` entry in a channel specification map lists all the
functions that a given channel offers. In order to work well with
<<effects#function-effects,Function Effects>> and
<<cues#creating-function-cues,Function Cues>> it is best to provide a
function list even for channels which only perform a single function.
A function list is a list of maps, each of which identifies a range of
values that do something when the channel is set to a value within
that range. Each map has the following content:

[cols="2l,5a", options="header"]
|===
|Key
|Purpose

|:start

|The beginning of the function range: the lowest DMX value which
 activates this function on the channel. Must be a legal DMX value,
 from `0` to `255`, and less than or equal to `:end`. Ranges must not
 overlap, so this value must be greater than the `:end` value of any
 other function range defined for the channel.

|:end

|The end of the function range: the highest DMX value which activates
 this function on the channel. Must be a legal DMX value, from `0` to
 `255`, and greater than or equal to `:start`. Ranges must not
 overlap, so this value must be less than the `:start` value of any
 other function range defined for the channel.

|:type

|A keyword which identifies the nature of the function. This is how
 <<effects#function-effects,Function Effects>> and
 <<cues#creating-function-cues,Function Cues>> will find the effect,
 so it is important to be consistent when assigning function types.
 The list of <<standard-function-types,standard function types>> is a
 good starting point. If you feel there is a common kind of function
 which should be added to that list, please open an
 https://github.com/brunchboy/afterglow/issues[issue] requesting it.

|:range

|Tells Afterglow what kind of a function range this is. Some functions
 are simply either off or on, and even if multiple DMX values exist
 within the function range, the result of using any of them is no
 different from using another. Such functions are identified by a
 `:range` type of `:fixed`. Other functions, such as a rotation speed
 or focus, will have different effects for every value in the range,
 and are identified by a `:range` type of `:variable`. This helps
 Afterglow build an appropriate user interface for interacting with
 <<effects#function-effects,Function Effects>> in places like the
 <<mapping_sync#effect-control,Ableton Push Effect Control interface>>.

|:label

|Specifies a label that should be used when creating a user interface
 for adjusting this function. <<cues#creating-function-cues,Function
 Cues>> will use this as the label for the cue-local variable they
 create, and it will appear in places like the
 <<mapping_sync#effect-control,Ableton Push Effect Control interface>>.

|:scale-fn

|A function that will be called to scale the function value being
 requested by an effect. For functions whose `:range` is `:variable`,
 Afterglow function effects can vary the value being sent to activate
 the function. They normally do this as a percentage, where 0 maps to
 the `:start` of the range, and 100 maps to the `:end`, and values in
 between are scaled appropriately.

If there is a reason to tweak the values on the way in, you can store
a function at this key in the function specification, and Afterglow
will call the function with the percentage value the effect requested,
and expect the function to return a modified percentage value to use
to actually pick the DMX value to send. A good example of a reason to
do this is with the `strobe` function, so that different fixtures can
be coaxed into strobing at roughly the same rate. The fixture
definitions that ship with Afterglow use
http://deepsymmetry.org/afterglow/doc/afterglow.effects.channel.html#var-function-value-scaler[afterglow.effects.channel/function-value-scaler]
to build `:scale-fn` functions for their `:strobe` functions so that,
rather than a percentage, the strobe function value is interpreted as
an approximate Hz rate (flashes per second), normalized for each
fixture.

|===

== Channel Creation Functions

TODO: Finish this page.

* Explain how to create function specifications in all their variations,
with range helpers, etc., and list naming conventions established so
far, so that new fixtures can participate when they have similar
capabilities.

## Standard Function Types

<<effects#function-effects,Function Effects>> and
<<cues#creating-function-cues,Function Cues>> trigger and control
specific functions, potentially across a range of different fixture
types from different manufacturers. In order for that to work, the
<<function-specifications,Function Specifications>> must be created
with consistent `:type` keywords. When you are creating a new fixture
definition, check to see if any of the functions that it provides are
covered by this table, and if so, use the same keywords to identify
them, so your fixture can participate with other fixtures in effects
using that function.

If your function does not fit into this list, make up a keyword that
makes sense for it, following the style shown here. And also please
consider (if the function type is likely to be present on other
fixtures and useful to other people) opening an
https://github.com/brunchboy/afterglow/issues[issue] requesting that
your new function type be added to this list so that when other people
create definitions for similar fixtures, they can interoperate with
yours.

[cols="2l,5a", options="header"]
|===
|Function Key
|Description

|:dimmer

|Controls the overall brightness of the fixture or head, independent
 of any color intensity channels which might also affect it. This is
 also a fundamental channel type in Afterglow, and has a category of
 <<effects#dimmer-effects,Dimmer Effects>> to work with it.

|:red
:green
:blue
:white
:amber
:uv

|These identify functions (usually entire channels) which control the
 intensity of a particular color, usually on LED fixtures. When you
 create a channel of type `:color`, it will have a `:color` key with
 this value, and a corresponding function range. If your fixture has
 LEDs of colors other than these, use the color name to identify the
 function. (This will happen automatically when you use the
 http://deepsymmetry.org/afterglow/doc/afterglow.channels.html#var-color[color]
 channel <<channel-creation-functions,creation function>> to create
 the channel. Color channels are fundamental channel types in
 Afterglow, and the colors `:red`, `:green`, `:blue`, and `:white`
 will automatically participate in the color mixing Afterglow performs
 with <<effects#color-effects,Color Effects>>. The others can too if,
 as described <<hue-mixing,above>>, the `:color` channel has a `:hue`
 entry.

|:pan
:tilt

|Rotates the fixture about its Y (in the case of `:pan`) or X (in the
 case of `:tilt`) axis. These are also fundamental channel types in
 Afterglow, and have categories of
 <<effects#direction-effects,Direction Effects>> and
 <<effects#aim-effects,Aim Effects>> to work with them.

|:strobe

|Causes the fixture to flash on and off abruptly (and usually
 rapidly). This is typically a variable-range function, so different
 values within the function range cause the fixture to strobe at
 different speeds. If possible, use a `:scale-fn` function (with the
 help of
 http://deepsymmetry.org/afterglow/doc/afterglow.effects.channel.html#var-function-value-scaler[afterglow.effects.channel/function-value-scaler])
 when creating a strobe function so that the function level is
 interpreted as an approximate Hz rate for the strobe, and your new
 fixture will strobe in rough tandem with other fixtures being
 strobed. Take a look at the strobe function definitions for the
 existing fixtures for examples how to do this. All you need to do is
 measure the slowest and fastest rates at which your fixture actually
 strobes, as best you can, and use them like this:

[source,clojure]
----
(chan/functions :strobe 7
                0 nil
                11 {:type :strobe
                    :scale-fn (partial function-value-scaler 0.66 25)
                    :label "Strobe (0.66Hz->25Hz)"
                    :range :variable})
----

In this example, the fixture's strobe channel is at offset `7`, and
the range from `0`-`10` does not strobe, while at `11` it begins to
strobe approximately 0.66 times per second (or twice every three
seconds), and strobes faster for higher values, finally reaching
around 25 times per second at the maximum legal DMX value of 255.

|:focus

|Adjusts the focal plane of the fixture, usually a moving-head spot
 with the ability to project gobos (templates).

|:frost

|Controls a frost effect, softening the beam of light.

|:iris

|Controls the iris size, widening or narrowing the beam of light.

|:zoom

|Adjusts the rate at which the beam spreads as it travels further from the fixture.

|:sound-active

|Puts the fixture in a mode where it decides what to do by listening
 to music in the environment, rather than being directly controlled by
 its DMX channels.

|===
