site:
  title: Afterglow Developer Guide
  url: https://afterglow-guide/deepsymmetry.org/
  start_page: afterglow::README.adoc
content:
  sources:
  - url: https://github.com/Deep-Symmetry/afterglow.git
    branches: [main, guide*]
    start_path: doc
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
asciidoc:
  attributes:
    api-doc: https://afterglow-guide.deepsymmetry.org/api/
    icons: font
    experimental: ''
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle-3.zip
    snapshot: true
