= Videos
James Elliott <james@deepsymmetry.org>

ifdef::env-github[]
// Set up support for relative links and images on GitHub, even though
// the documentation is now designed for Antora. Also, need to add
// the API doc path here, since Antora takes care of it outside of
// GitHub. Hopefully we can eventually make this an include file, once
// GitHub *finally* supports those.
:outfilesuffix: .adoc
:imagesdir: ../assets/images
:api-doc: http://deepsymmetry.org/afterglow/api-doc/
endif::[]

This page collects performance videos that highlight Afterglow in
action. If you have any to share, please post them to the
https://gitter.im/brunchboy/afterglow[Afterglow room on Gitter]!

Since I have been too busy working on the software to get out and
perform with it, I am deeply grateful to
https://github.com/dandaka[Vlad Rafeev] for getting this page started
by sharing a video of a
https://www.facebook.com/deepowerband/[Deepower audiovisual] show he
lit using Afterglow in Kaliningrad, in December, 2015. He modestly
says, “My first experience with lights, still a lot to accomplish.”
And I say, there is a ton left to implement in the software too. But
it is already fun to see https://vimeo.com/153492480[great video like
this]!

For a more wordy and nerdy introduction, there is a video of my
https://youtu.be/mvNN0SMMZDQ[presentation and demonstration] at the
June 2016
http://www.meetup.com/Madison-Clojure-Meetup/events/229842513/[Madison
Clojure Meetup].

include::partial$Footer.adoc[]
